# Docker image for springboot file run
# VERSION 0.0.1
# Author: qiran
# 基础镜像使用java
FROM java:8
# 作者
MAINTAINER qiran <1024418684@qq.com>
# VOLUME 指定了临时文件目录为/tmp。
# 其效果是在主机 /var/lib/docker 目录下创建了一个临时文件，并链接到容器的/tmp
VOLUME /tmp 

EXPOSE 9001
# 将jar包添加到容器中并更名为app.jar
COPY /root/workspace/springCloudTest/springcloud-2.0-eureka-9001/target/springcloud-2.0-eureka-9001.jar springcloud-2.0-eureka-9001.jar 
# 运行jar包
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/springcloud-2.0-eureka-9001.jar"]